<a href="https://colab.research.google.com/github/adas754/ann_class/blob/main/REGEX.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# REGEX

## What is Regex (Regular Expressions)?
       Regex (short for Regular Expressions) is like a search pattern used to match text.

     1.It’s basically a sequence of characters that defines a rule for finding strings inside text.

     2.Think of it like a CTRL+F on steroids → much more powerful than normal search.

## Why Do We Need Regex?
-- In Machine Learning, Regex is not a model, but a preprocessing / feature engineering tool.We use it mostly in text-based ML tasks (NLP).

We need regex when we want to:

  1. Search → Find a pattern in text

  2. Validate → Check if input follows rules

  3. Extract → Pull out useful pieces of text

  4. Replace/Clean → Modify text based on patterns

---

# 📝 **Regex Cheat Sheet**

###  **Basic Patterns**

| Regex | Meaning                          | Example              |
| ----- | -------------------------------- | -------------------- |
| `.`   | Any character except newline     | `c.t` → `cat`, `cut` |
| `\d`  | Digit (0–9)                      | `\d\d` → `42`        |
| `\D`  | Not a digit                      | `\D+` → `abc`        |
| `\w`  | Word char (letters, digits, `_`) | `\w+` → `Hello123`   |
| `\W`  | Not a word char                  | `@#$`                |
| `\s`  | Whitespace (space, tab, newline) | `" a b "`            |
| `\S`  | Non-whitespace                   | `"abc"`              |

---

###  **Anchors (Position)**

| Regex | Meaning         | Example                                 |
| ----- | --------------- | --------------------------------------- |
| `^`   | Start of string | `^Hello` → `"Hello world"`              |
| `$`   | End of string   | `world$` → `"Hello world"`              |
| `\b`  | Word boundary   | `\bcat\b` → `"cat"` but not `"scatter"` |

---

###  **Quantifiers**

| Regex   | Meaning         | Example                         |
| ------- | --------------- | ------------------------------- |
| `*`     | 0 or more       | `a*` → `""`, `"a"`, `"aaa"`     |
| `+`     | 1 or more       | `a+` → `"a"`, `"aaa"`           |
| `?`     | 0 or 1          | `a?` → `""`, `"a"`              |
| `{n}`   | Exactly n       | `\d{3}` → `123`                 |
| `{n,}`  | n or more       | `\d{2,}` → `12345`              |
| `{n,m}` | Between n and m | `\d{2,4}` → `12`, `123`, `1234` |

---

###  **Character Sets**

| Regex    | Meaning              | Example     |
| -------- | -------------------- | ----------- |
| `[abc]`  | Match a, b, or c     | `cat` → `c` |
| `[^abc]` | NOT a, b, or c       | `dog`       |
| `[a-z]`  | Any lowercase letter | `m`         |
| `[A-Z]`  | Any uppercase letter | `G`         |
| `[0-9]`  | Any digit            | `7`         |

---

###  **Groups & Alternation**

| Regex   | Meaning | Example              |       |               |
| ------- | ------- | -------------------- | ----- | ------------- |
| `(abc)` | Group   | `(ab)+` → `"ababab"` |       |               |
| \`a     | b\`     | OR → a or b          | \`cat | dog`→`"dog"\` |

---

###  **Useful Real-World Patterns**

| Regex                                         | Used For          | Example Match        |
| --------------------------------------------- | ----------------- | -------------------- |
| `\d{10}`                                      | 10-digit phone    | `9876543210`         |
| `[A-Za-z0-9._%+-]+@[A-Za-z.-]+\.[A-Za-z]{2,}` | Email             | `test@mail.com`      |
| `\d{2}/\d{2}/\d{4}`                           | Date (dd/mm/yyyy) | `22/09/2025`         |
| `https?://\S+`                                | URL               | `http://example.com` |

---

 **Tip**: Always test regex online before using → [regex101.com](https://regex101.com/)

---

Do you want me to make a **visual infographic-style version** of this cheat sheet (good for presentations/teaching)?

In [1]:
import pandas as pd  # Import the Pandas library for data manipulation

# Load the CSV file into a DataFrame
df = pd.read_csv("/content/reviews.csv")

# Display the first 5 rows of the DataFrame
df.head()

,ID,Name,Email,Phone,Review
0,1,John Doe,john.doe@example.com,9876543210,I love Python!!! #AI #ML
1,2,Jane Smith,jane.smith@example.com,9123456789,"Worst experience 😡, never coming back!"
2,3,Bob Johnson,bob.j@example.com,9988776655,Check out my blog: https://example.com
3,4,Alice Brown,alice.b@example.com,9871122334,Amazing service!!! 5 stars ⭐⭐⭐⭐⭐
4,5,Charlie Lee,charlie.l@example.com,9765432109,"Not satisfied, needs improvement."

In [2]:
import re  # Import the regular expressions module for text pattern matching

In [3]:
# Display reviews that start with the word "love" (case-insensitive)
df[df['Review'].str.contains(r"^love", flags=re.IGNORECASE, regex=True)]

,ID,Name,Email,Phone,Review
8,9,Grace Hall,grace.h@example.com,9321098765,"Loved the experience, highly recommend."
24,25,Wendy Lewis,wendy.l@example.com,9543210984,Loved the colors and design.

In [5]:
# Display email addresses that start with "bob"
df[df['Email'].str.contains(r'^bob', regex=True)]

,ID,Name,Email,Phone,Review
2,3,Bob Johnson,bob.j@example.com,9988776655,Check out my blog: https://example.com

In [6]:
# Display phone numbers that start with "9"
df[df['Phone'].astype(str).str.contains(r'^9', regex=True)]

,ID,Name,Email,Phone,Review
0,1,John Doe,john.doe@example.com,9876543210,I love Python!!! #AI #ML
1,2,Jane Smith,jane.smith@example.com,9123456789,"Worst experience 😡, never coming back!"
2,3,Bob Johnson,bob.j@example.com,9988776655,Check out my blog: https://example.com
3,4,Alice Brown,alice.b@example.com,9871122334,Amazing service!!! 5 stars ⭐⭐⭐⭐⭐
4,5,Charlie Lee,charlie.l@example.com,9765432109,"Not satisfied, needs improvement."
5,6,David Kim,david.k@example.com,9654321098,"Great product, will buy again!"
6,7,Eve Davis,eve.d@example.com,9543210987,"Terrible delivery, very late!"
7,8,Frank Moore,frank.m@example.com,9432109876,Excellent support and guidance.
8,9,Grace Hall,grace.h@example.com,9321098765,"Loved the experience, highly recommend."
9,10,Hank Allen,hank.a@example.com,9210987654,"Poor packaging, item damaged."
10,11,Ivy Scott,ivy.s@example.com,9109876543,Amazing quality for the price.
11,12,Jack White,jack.w@example.com,9898765432,Delivery was fast and efficient.
12,13,Karen Young,karen.y@example.com,9787654321,Customer service could be better.
13,14,Liam King,liam.k@example.com,9676543210,"Fantastic features, very useful."
14,15,Mia Wright,mia.w@example.com,9565432109,Disappointed with the color options.
15,16,Noah Hill,noah.h@example.com,9454321098,Easy to use and reliable.
16,17,Olivia Green,olivia.g@example.com,9343210987,Not worth the money.
17,18,Paul Adams,paul.a@example.com,9232109876,"Highly satisfied, will order again."
18,19,Quinn Baker,quinn.b@example.com,9121098765,Product arrived as described.
19,20,Rachel Clark,rachel.c@example.com,9010987654,Customer support was unhelpful.
20,21,Sam Evans,sam.e@example.com,9987654321,Very user-friendly interface.
21,22,Tina Foster,tina.f@example.com,9876543211,Shipping took too long.
22,23,Uma Harris,uma.h@example.com,9765432102,Excellent quality and service.
23,24,Victor Jones,victor.j@example.com,9654321093,"Poor instructions, hard to assemble."
24,25,Wendy Lewis,wendy.l@example.com,9543210984,Loved the colors and design.
25,26,Xander Miller,xander.m@example.com,9432109875,Battery life is short.
26,27,Yara Nelson,yara.n@example.com,9321098766,Great value for money.
27,28,Zack Owens,zack.o@example.com,9210987657,"Not as described, disappointed."
28,29,Alice Perry,alice.p@example.com,9109876548,Fast delivery and good packaging.
29,30,Brian Quinn,brian.q@example.com,9898765439,Amazing! Exceeded my expectations.

In [7]:
# Display names that start with a vowel
df[df['Name'].str.contains(r'^[AEIOUaeiou]', regex=True)]

,ID,Name,Email,Phone,Review
3,4,Alice Brown,alice.b@example.com,9871122334,Amazing service!!! 5 stars ⭐⭐⭐⭐⭐
6,7,Eve Davis,eve.d@example.com,9543210987,"Terrible delivery, very late!"
10,11,Ivy Scott,ivy.s@example.com,9109876543,Amazing quality for the price.
16,17,Olivia Green,olivia.g@example.com,9343210987,Not worth the money.
22,23,Uma Harris,uma.h@example.com,9765432102,Excellent quality and service.
28,29,Alice Perry,alice.p@example.com,9109876548,Fast delivery and good packaging.

In [11]:
# Display email addresses that end with "example.com"
df[df['Email'].str.contains(r'example.com$', regex=True)]

,ID,Name,Email,Phone,Review
0,1,John Doe,john.doe@example.com,9876543210,I love Python!!! #AI #ML
1,2,Jane Smith,jane.smith@example.com,9123456789,"Worst experience 😡, never coming back!"
2,3,Bob Johnson,bob.j@example.com,9988776655,Check out my blog: https://example.com
3,4,Alice Brown,alice.b@example.com,9871122334,Amazing service!!! 5 stars ⭐⭐⭐⭐⭐
4,5,Charlie Lee,charlie.l@example.com,9765432109,"Not satisfied, needs improvement."
5,6,David Kim,david.k@example.com,9654321098,"Great product, will buy again!"
6,7,Eve Davis,eve.d@example.com,9543210987,"Terrible delivery, very late!"
7,8,Frank Moore,frank.m@example.com,9432109876,Excellent support and guidance.
8,9,Grace Hall,grace.h@example.com,9321098765,"Loved the experience, highly recommend."
9,10,Hank Allen,hank.a@example.com,9210987654,"Poor packaging, item damaged."
10,11,Ivy Scott,ivy.s@example.com,9109876543,Amazing quality for the price.
11,12,Jack White,jack.w@example.com,9898765432,Delivery was fast and efficient.
12,13,Karen Young,karen.y@example.com,9787654321,Customer service could be better.
13,14,Liam King,liam.k@example.com,9676543210,"Fantastic features, very useful."
14,15,Mia Wright,mia.w@example.com,9565432109,Disappointed with the color options.
15,16,Noah Hill,noah.h@example.com,9454321098,Easy to use and reliable.
16,17,Olivia Green,olivia.g@example.com,9343210987,Not worth the money.
17,18,Paul Adams,paul.a@example.com,9232109876,"Highly satisfied, will order again."
18,19,Quinn Baker,quinn.b@example.com,9121098765,Product arrived as described.
19,20,Rachel Clark,rachel.c@example.com,9010987654,Customer support was unhelpful.
20,21,Sam Evans,sam.e@example.com,9987654321,Very user-friendly interface.
21,22,Tina Foster,tina.f@example.com,9876543211,Shipping took too long.
22,23,Uma Harris,uma.h@example.com,9765432102,Excellent quality and service.
23,24,Victor Jones,victor.j@example.com,9654321093,"Poor instructions, hard to assemble."
24,25,Wendy Lewis,wendy.l@example.com,9543210984,Loved the colors and design.
25,26,Xander Miller,xander.m@example.com,9432109875,Battery life is short.
26,27,Yara Nelson,yara.n@example.com,9321098766,Great value for money.
27,28,Zack Owens,zack.o@example.com,9210987657,"Not as described, disappointed."
28,29,Alice Perry,alice.p@example.com,9109876548,Fast delivery and good packaging.
29,30,Brian Quinn,brian.q@example.com,9898765439,Amazing! Exceeded my expectations.

In [12]:
# Display phone numbers that end with "5"
df[df['Phone'].astype(str).str.contains(r'5$', regex=True, na=False)]

,ID,Name,Email,Phone,Review
2,3,Bob Johnson,bob.j@example.com,9988776655,Check out my blog: https://example.com
8,9,Grace Hall,grace.h@example.com,9321098765,"Loved the experience, highly recommend."
18,19,Quinn Baker,quinn.b@example.com,9121098765,Product arrived as described.
25,26,Xander Miller,xander.m@example.com,9432109875,Battery life is short.

In [13]:
# Replace '@' and '.' with '_' in the Email column
df['Email'] = df['Email'].str.replace(r'[@.]', '_', regex=True)

In [ ]:
df

,ID,Name,Email,Phone,Review
0,1,John Doe,john_doe_example_com,9876543210,I love Python!!! #AI #ML
1,2,Jane Smith,jane_smith_example_com,9123456789,"Worst experience 😡, never coming back!"
2,3,Bob Johnson,bob_j_example_com,9988776655,Check out my blog: https://example.com
3,4,Alice Brown,alice_b_example_com,9871122334,Amazing service!!! 5 stars ⭐⭐⭐⭐⭐
4,5,Charlie Lee,charlie_l_example_com,9765432109,"Not satisfied, needs improvement."
5,6,David Kim,david_k_example_com,9654321098,"Great product, will buy again!"
6,7,Eve Davis,eve_d_example_com,9543210987,"Terrible delivery, very late!"
7,8,Frank Moore,frank_m_example_com,9432109876,Excellent support and guidance.
8,9,Grace Hall,grace_h_example_com,9321098765,"Loved the experience, highly recommend."
9,10,Hank Allen,hank_a_example_com,9210987654,"Poor packaging, item damaged."
10,11,Ivy Scott,ivy_s_example_com,9109876543,Amazing quality for the price.
11,12,Jack White,jack_w_example_com,9898765432,Delivery was fast and efficient.
12,13,Karen Young,karen_y_example_com,9787654321,Customer service could be better.
13,14,Liam King,liam_k_example_com,9676543210,"Fantastic features, very useful."
14,15,Mia Wright,mia_w_example_com,9565432109,Disappointed with the color options.
15,16,Noah Hill,noah_h_example_com,9454321098,Easy to use and reliable.
16,17,Olivia Green,olivia_g_example_com,9343210987,Not worth the money.
17,18,Paul Adams,paul_a_example_com,9232109876,"Highly satisfied, will order again."
18,19,Quinn Baker,quinn_b_example_com,9121098765,Product arrived as described.
19,20,Rachel Clark,rachel_c_example_com,9010987654,Customer support was unhelpful.
20,21,Sam Evans,sam_e_example_com,9987654321,Very user-friendly interface.
21,22,Tina Foster,tina_f_example_com,9876543211,Shipping took too long.
22,23,Uma Harris,uma_h_example_com,9765432102,Excellent quality and service.
23,24,Victor Jones,victor_j_example_com,9654321093,"Poor instructions, hard to assemble."
24,25,Wendy Lewis,wendy_l_example_com,9543210984,Loved the colors and design.
25,26,Xander Miller,xander_m_example_com,9432109875,Battery life is short.
26,27,Yara Nelson,yara_n_example_com,9321098766,Great value for money.
27,28,Zack Owens,zack_o_example_com,9210987657,"Not as described, disappointed."
28,29,Alice Perry,alice_p_example_com,9109876548,Fast delivery and good packaging.
29,30,Brian Quinn,brian_q_example_com,9898765439,Amazing! Exceeded my expectations.